--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Nov 03 2020 12:03
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Note'   
-- NoteId          :  
--
CREATE TABLE Note (
    NoteId         BIGINT IDENTITY(1,1) NOT NULL,
CONSTRAINT pk_Note PRIMARY KEY CLUSTERED (NoteId))